# Generated by Django 4.1.1 on 2022-09-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('red', 'red'), ('grn', 'green'), ('blu', 'blue'), ('blk', 'black'), ('wht', 'white'), ('ylw', 'yellow'), ('gry', 'grey'), ('pnk', 'pink'), ('org', 'orange'), ('chm', 'chrome'), ('ctm', 'custom')], default='blk', max_length=3)),
                ('mileage', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('year', models.IntegerField()),
                ('is_new', models.BooleanField(default=True)),
                ('fuel', models.CharField(choices=[('gas', 'gasoline'), ('dsl', 'diesel'), ('elt', 'electric'), ('hbd', 'hybrid')], default='gas', max_length=3)),
                ('engine', models.CharField(blank=True, max_length=255, null=True)),
                ('automatic_transmission', models.BooleanField(default=True)),
                ('gears', models.IntegerField()),
                ('type', models.CharField(choices=[('c', 'car'), ('m', 'motorcycle')], default='c', max_length=1)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
