# Generated by Django 4.1.1 on 2022-09-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_is_turbo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_turbo',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('Aspirated', 'Aspirated'), ('Turbo', 'Turbo'), ('Biturbo', 'Biturbo'), ('Quadturbo', 'Quadturbo'), ('Supercharged', 'Supercharged')], default='Aspirated', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow'), ('Grey', 'Grey'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Chrome', 'Chrome'), ('Custom', 'Custom')], default='Red', max_length=255),
        ),
    ]
