# Generated by Django 4.1.1 on 2022-09-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.AddField(
            model_name='model',
            name='type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle')], default='Car', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(choices=[('I3 1.0', 'I3 1.0'), ('I3 1.6', 'I3 1.6'), ('I4 1.0', 'I4 1.0'), ('I4 1.6', 'I4 1.6'), ('I4 2.0', 'I4 2.0'), ('I4 2.2', 'I4 2.2'), ('I4 2.5', 'I4 2.5'), ('I6 3.0', 'I6 3.0'), ('V6 3.0', 'V6 3.0'), ('V6 3.3', 'V6 3.3'), ('V8 4.0', 'V8 4.0'), ('V8 5.0', 'V8 5.0'), ('V8 6.0', 'V8 6.0'), ('V8 7.0', 'V8 7.0'), ('V8 8.0', 'V8 8.0'), ('V10', 'V10'), ('V12', 'V12'), ('W16', 'W16'), ('Battery', 'Battery'), ('Custom', 'Custom')], default='I3 1.0', max_length=255),
        ),
    ]
